### ISSUE TITLE
To be done on database

### ISSUE THREAD

**Issue by ks-manu** [BalliMontero/Mannschaft_KNUST#1]
1. Table has not been designed to store messages and votes
2. No storage for media has been decided upon for files
3. Messages, Votes, Files need unique ID's which identify them as belonging to a particular message board for easy retrieval by other members

**Comment by SarahMens** [comment]
The message and votes tables have been created but for the media for files,  I'm yet to do them

**Comment by ks-manu** [comment]
Great

Please check comments and suggestions in database V 1.0.1.2 let's discuss
