### ISSUE TITLE
Web Form authentication

### ISSUE THREAD

**Issue by ceesiyamoah** [BalliMontero/Mannschaft_KNUST#4]

**Comment by ks-manu** [comment]
Hi, please provide a description

**Comment by ks-manu** [comment]
The API authentication works fine. Just clone the API folder and run the server file named: mainRouter-1.js. However, you have to create your own database

Let me know if you have any challenges.

**Comment by the-maazu** [comment]
cannot run. mainRouter-1.js contains unresolved merge conflicts.

**Comment by ks-manu** [comment]
Merge conflicts resolved
